### ISSUE TITLE
Is GELU operation quantized as well?

### ISSUE THREAD

**Issue by Kevinpsk** [linyang-zhh/FQ-ViT#2]
Hi there, 

Thanks a lot for sharing the coding. 
I have a quick question, is GELU layer fully quantized as well? I see you mention that the vision transformer is fully quantized, but I was not able to find where you quantize GELU in code, nor do I find any description of it in the paper? Did I miss something? 
Thanks a lot for your clarification.

**Comment by linyang-zhh** [comment]
@Kevinpsk
Hi! Thanks for your interest in our work!

We quantize the output of GELU using the `QAct`, the code is [here](https://github.com/linyang-zhh/FQ-ViT/blob/16122ee7ea33e80aed3edd29cfebb3ab2ce2cb69/models/layers_quant.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L174).

This processing is consistent with the actual application. Considering that PTQ must guarantee the quantized inference is consistent with the original full-precision inference, we must keep the non-linear GELU layer. Thus, to minimize hardware consumption for subsequent operations (e.g., the next linear operation), quantization is usually performed on the output of GELU, and the inference of the GELU function is performed in a cpu unit, or implemented using a Look-Up-Table (LUT).

If you are interested in a purely fixed-point implementation of the inference of GELU, we recommend you to follow the work of [I-BERT](https://github.com/kssteven418/I-BERT), and also welcome to try our optimizations for LayerNorm and Softmax!
