### ISSUE TITLE
SwinTransformer3D

### ISSUE THREAD

**Issue by wangjingg** [linyang-zhh/FQ-ViT#4]
Does this framework support SwinTransformer3D quantification?

**Comment by linyang-zhh** [comment]
@wangjingg 
The motivations of our work is based on the serious inter-channel variation in some layers of transformer architectures, and we propose a series of methods to solve that.
Our experiments are tested on 2D transformers such as ViT and Swin. So far, we don't know whether SwinTransformer3D has such characteristic too, so maybe, additional evaluation is required.
