### ISSUE TITLE
Input quantization

### ISSUE THREAD

**Issue by xqjiang423** [linyang-zhh/FQ-ViT#7]
Hi, I was wondering if the inputs are quantized as well? Does Quantization just cover the weights, LayerNorm and activations? Thanks!

**Comment by linyang-zhh** [comment]
@xqjiang423 Hi!
Inputs are also quantized. You can check it in [this line](https://github.com/linyang-zhh/FQ-ViT/blob/16122ee7ea33e80aed3edd29cfebb3ab2ce2cb69/models/swin_quant.py#L568). 

As for the second question, we quantize all modules, which include LayerNorm, Softmax and weights/activations in Conv/Linear layers.
